---
name: Build CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --name=mongodb
    env:
      MONGODB_URL: mongodb://localhost:27017/acebook_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint and unit tests
        run: |
          npm run lint
          npm run test:unit
      - name: Run integration tests
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
          start: npm run start:ci
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install SSH client and rsync
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-client rsync
      - name: Set up SSH agent and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          rsync -av -e "ssh -o StrictHostKeyChecking=no" ./* ec2-user@${{ secrets.EC2_1_IP }}:/var/acebook/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_1_IP }} "sudo systemctl restart acebook"
          rsync -av -e "ssh -o StrictHostKeyChecking=no" ./* ec2-user@${{ secrets.EC2_2_IP }}:/var/acebook/
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_2_IP }} "sudo systemctl restart acebook"
          